# Generated by Django 2.0.3 on 2018-03-20 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(help_text='What are your thoughts..', max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Birthday')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('f', 'FEED'), ('s', 'SERVICE'), ('m', 'MAP')], max_length=1)),
                ('title', models.CharField(max_length=150)),
                ('text', models.CharField(max_length=150)),
                ('createdOn', models.DateField()),
                ('latitude', models.CharField(max_length=45)),
                ('longitude', models.CharField(max_length=45)),
                ('expiry', models.DateField()),
                ('cost', models.IntegerField()),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('comments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pawpular.Comment')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signUpDate', models.DateField()),
                ('lname', models.CharField(max_length=45)),
                ('fname', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
                ('settings', models.CharField(max_length=45)),
                ('friends', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pawpular.User')),
                ('pets', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pawpular.Pet')),
                ('posts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pawpular.Post')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='createdBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pawpular.User'),
        ),
        migrations.AddField(
            model_name='pet',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pawpular.User'),
        ),
    ]
