# Generated by Django 2.0.3 on 2018-04-23 01:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('text', models.TextField(help_text='What are your thoughts..', max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='FeedPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('text', models.TextField(max_length=150)),
                ('image', models.ImageField(upload_to='uploads/')),
                ('createdOn', models.DateField()),
                ('title', models.CharField(default='', max_length=50)),
                ('post', models.CharField(default='', max_length=1000)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MapPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('text', models.TextField(max_length=150)),
                ('image', models.ImageField(upload_to='uploads/')),
                ('createdOn', models.DateField()),
                ('title', models.CharField(default='', max_length=50)),
                ('latitude', models.CharField(default='', max_length=45)),
                ('longitude', models.CharField(default='', max_length=45)),
                ('expiry', models.DateField(default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, upload_to='uploads/')),
                ('name', models.CharField(max_length=45)),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Birthday')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, upload_to='uploads/')),
                ('settings', models.CharField(choices=[('1', 'on'), ('0', 'off')], default='1', help_text='settings status status', max_length=1)),
                ('feedPosts', models.ManyToManyField(blank=True, to='pawpular.FeedPost')),
                ('mapPosts', models.ManyToManyField(blank=True, to='pawpular.MapPost')),
                ('pets', models.ManyToManyField(blank=True, to='pawpular.Pet')),
            ],
        ),
        migrations.CreateModel(
            name='ServicePost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('text', models.TextField(max_length=150)),
                ('image', models.ImageField(upload_to='uploads/')),
                ('createdOn', models.DateField()),
                ('title', models.CharField(default='', max_length=50)),
                ('cost', models.IntegerField(blank=True)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pawpular.Profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='servicePosts',
            field=models.ManyToManyField(blank=True, to='pawpular.ServicePost'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pet',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pawpular.Profile'),
        ),
        migrations.AddField(
            model_name='mappost',
            name='createdBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pawpular.Profile'),
        ),
        migrations.AddField(
            model_name='feedpost',
            name='createdBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pawpular.Profile'),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ManyToManyField(blank=True, to='pawpular.FeedPost'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pawpular.Profile'),
        ),
    ]
