# Generated by Django 2.0.2 on 2018-03-20 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pawpular', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='pets',
        ),
    ]
