# Generated by Django 2.0.2 on 2018-04-23 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawpular', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedpost',
            name='post',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
