# Generated by Django 2.0.2 on 2018-03-20 23:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pawpular', '0002_auto_20180320_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=150)),
                ('createdOn', models.DateField()),
                ('title', models.CharField(default='', max_length=150)),
                ('latitude', models.CharField(default='', max_length=45)),
                ('longitude', models.CharField(default='', max_length=45)),
                ('expiry', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='post',
            name='createdBy',
        ),
        migrations.RemoveField(
            model_name='user',
            name='posts',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AddField(
            model_name='mappost',
            name='createdBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pawpular.User'),
        ),
    ]
