# Generated by Django 2.0.2 on 2018-04-23 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawpular', '0002_auto_20180422_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedpost',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='mappost',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='servicepost',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
    ]
