# Generated by Django 2.0.2 on 2018-04-29 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pawpular', '0003_auto_20180422_2349'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedpost',
            options={'ordering': ['-createdOn']},
        ),
        migrations.AlterModelOptions(
            name='mappost',
            options={'ordering': ['-createdOn']},
        ),
        migrations.AlterModelOptions(
            name='servicepost',
            options={'ordering': ['-createdOn']},
        ),
    ]
