# Generated by Django 2.0.2 on 2018-03-20 23:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pawpular', '0003_auto_20180320_1911'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=150)),
                ('createdOn', models.DateField()),
                ('test', models.CharField(default='SOME STRING', max_length=150)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServicePost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=150)),
                ('createdOn', models.DateField()),
                ('title', models.CharField(default='SOME STRING', max_length=150)),
                ('cost', models.IntegerField(default='SOME STRING')),
                ('startDate', models.DateField(default='SOME STRING')),
                ('endDate', models.DateField(default='SOME STRING')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='friends',
        ),
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(to='pawpular.User'),
        ),
        migrations.AddField(
            model_name='servicepost',
            name='createdBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pawpular.User'),
        ),
        migrations.AddField(
            model_name='feedpost',
            name='createdBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pawpular.User'),
        ),
    ]
