# Generated by Django 2.0.2 on 2018-04-29 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pawpular', '0004_auto_20180429_1453'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='feedpost',
            options={'ordering': ['-createdOn', 'createdBy']},
        ),
        migrations.AlterModelOptions(
            name='mappost',
            options={'ordering': ['-createdOn', 'createdBy']},
        ),
        migrations.AlterModelOptions(
            name='pet',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='servicepost',
            options={'ordering': ['-createdOn', 'createdBy']},
        ),
    ]
