# Generated by Django 2.0.2 on 2018-03-20 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pawpular', '0004_auto_20180320_1917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='text',
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pawpular.User'),
        ),
        migrations.AlterField(
            model_name='feedpost',
            name='test',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='servicepost',
            name='cost',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='servicepost',
            name='endDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='servicepost',
            name='startDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='servicepost',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(blank=True, to='pawpular.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pets',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='pawpular.Pet'),
        ),
    ]
