# Generated by Django 2.0.2 on 2018-03-20 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawpular', '0005_auto_20180320_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='settings',
            field=models.CharField(default='', max_length=45),
        ),
    ]
