# Generated by Django 2.0.2 on 2018-03-22 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pawpular', '0006_auto_20180320_1930'),
        ('pawpular', '0002_remove_user_pets'),
    ]

    operations = [
    ]
