# Generated by Django 2.0.2 on 2018-03-22 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pawpular', '0007_merge_20180322_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pets',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pawpular.Pet'),
        ),
    ]
