# Generated by Django 2.0.2 on 2018-03-24 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pawpular', '0008_user_pets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='pets',
        ),
    ]
