# Generated by Django 2.0.2 on 2018-03-24 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawpular', '0009_remove_user_pets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='settings',
            field=models.CharField(choices=[('1', 'on'), ('0', 'off')], default='1', help_text='security status', max_length=1),
        ),
    ]
