# Generated by Django 2.0.2 on 2018-03-24 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawpular', '0011_auto_20180324_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='name',
            field=models.CharField(blank=True, max_length=45),
        ),
    ]
