# Generated by Django 2.0.2 on 2018-03-24 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pawpular', '0012_manufacturer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='manufacturer',
        ),
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.DeleteModel(
            name='Manufacturer',
        ),
    ]
