# Generated by Django 2.0.2 on 2018-03-26 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawpular', '0014_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
    ]
