# Generated by Django 2.0.2 on 2018-03-27 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawpular', '0016_auto_20180326_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappost',
            name='imageurl',
            field=models.CharField(default='', max_length=150),
        ),
    ]
