# Generated by Django 2.0.3 on 2018-03-28 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pawpular', '0021_auto_20180327_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedpost',
            name='test',
        ),
    ]
