# Generated by Django 2.0.3 on 2018-03-28 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawpular', '0022_remove_feedpost_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ManyToManyField(blank=True, to='pawpular.FeedPost'),
        ),
        migrations.AddField(
            model_name='feedpost',
            name='comments',
            field=models.ManyToManyField(blank=True, to='pawpular.Comment'),
        ),
    ]
