# Generated by Django 2.0.2 on 2018-04-12 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pawpular', '0026_auto_20180405_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='AccountPointer',
        ),
    ]
