# Generated by Django 2.0.3 on 2018-04-17 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawpular', '0027_remove_user_accountpointer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
