# Generated by Django 2.0.3 on 2018-04-17 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pawpular', '0033_auto_20180416_2320'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={},
        ),
        migrations.AlterModelManagers(
            name='profile',
            managers=[
            ],
        ),
    ]
