# Generated by Django 2.0.2 on 2018-04-17 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawpular', '0034_auto_20180416_2324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedpost',
            name='comments',
        ),
        migrations.AddField(
            model_name='feedpost',
            name='post',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
