# Generated by Django 2.0.2 on 2018-04-17 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawpular', '0035_auto_20180417_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedpost',
            name='imageURL',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
