# Generated by Django 2.0.2 on 2018-04-17 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pawpular', '0036_auto_20180417_1558'),
        ('pawpular', '0036_feedpost_imageurl'),
    ]

    operations = [
    ]
