# Generated by Django 2.0.3 on 2018-04-20 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawpular', '0037_merge_20180417_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedpost',
            name='imageURL',
        ),
        migrations.RemoveField(
            model_name='mappost',
            name='imageUrl',
        ),
        migrations.AlterField(
            model_name='feedpost',
            name='image',
            field=models.ImageField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='mappost',
            name='image',
            field=models.ImageField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='servicepost',
            name='image',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
