# Generated by Django 2.0.2 on 2018-04-19 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pawpular', '0037_merge_20180417_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mappost',
            name='imageUrl',
        ),
    ]
