# Generated by Django 2.0.2 on 2018-04-21 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pawpular', '0038_auto_20180420_1208'),
        ('pawpular', '0038_remove_mappost_imageurl'),
    ]

    operations = [
    ]
